apiVersion: v1
kind: ConfigMap
metadata:
 name: default-page
 labels:
  app: default-page
data:
  index.html: |
   <!doctype html>   
    <html>  
      <head>  
       <meta charset="utf-8">  
        <title>Index Page</title>  
        <link rel="stylesheet" href="main.css">  
      </head>  
      <body>  
        <table class="class1">
          <tr>  
            <td class="class1">  
              <table class="class3">  
                <tr>
                  <td>
                    <h1>Code Education Rocks!!!!</h1>
                  </td>
                </tr>  
              </table>  
            </td>  
          </tr>      
        </table>  
      </body>
    </html>