apiVersion: apps/v1
kind: Deployment # Tipo do objeto

metadata:
 name: nginx-service # Nome do deploy
 labels:
  app: nginx-server

spec: # Especificações do deployment
 replicas: 3

 selector: # Selector utilizado para criar o service
  matchLabels:
   app: nginx-server

 template: #referente ao POD
  metadata:
   labels:
    app: nginx-server

  spec:
   containers:
   - name: nginx
     image: nginx:1.17-alpine
     ports:
     - containerPort: 80

     #Montagem do volume configmap
     volumeMounts:
     - name: default-page
       mountPath: /usr/share/nginx/html        
       readOnly: true

   volumes:
   - name: default-page
     configMap:
      name: default-page
      items:
       - key: index.html
         path: index.html